<?php
/**
 * Copyright © 2015 ipragmatechcommerce. All rights reserved.
 */
?>
<?php
/**
 * {{controller}} {{action}} template
 *
 * @var $block \Ipragmatech\Contactme\Block\Index\Index
 */

//https://www.tutorialrepublic.com/snippets/preview.php?topic=bootstrap&file=product-list-carousel-for-ecommerce-website
?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!-- <link rel="stylesheet" href="https://www.maxhealthcare.in/sites/all/themes/sub/max_theme/css/max-labs.css">
<link rel="stylesheet" href="https://www.maxhealthcare.in/sites/all/themes/sub/max_theme/css/campaign.css"> -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<style>
.page-title-wrapper {
    display: none;
}
  .page-wrapper{
    min-width: 100%;
  }
  .page-main{
    min-width: 100%;
    padding-left: 0;
    padding-right: 0;
  }
  .container{
      min-width: 100%;
  }
  header.navbar {
    border: 0 none;
    box-shadow: 0 0 7px 0 #999;
  }
  header#navbar.navbar-default {
    background-color: #FFFFFF;
    min-height: 84px;
    z-index: 99;

  }
  .navbar-header.header-scroll-logo {
    padding: 11px 0px;
    width: 100%;
  }
  header#navbar {
    padding-left: 0px;
  }
  .logo {
    max-width: 100%;
    height: auto;
    margin-bottom: 0px;
    float: left;
  }
  .contectme-widget{
    max-width: 300px;
  }
  .campaign-webform {
    z-index: inherit;
    right: 26px;
    height: auto;
    top: 26px;
    max-width: 300px;
    min-width: 150px;
    text-align: center;
    margin-right: 10px;
    top: 0 !important;
    background: #57b38f !important;
    border: 1px solid #EEE;
}


.contectme-widget-wrapper {
    position: absolute;
    top: 84px; */
    /* float: right; */
    margin-right: 25px;
    /* float: left; */
    z-index: 90;
    margin-left: 75%;
}
.slider {
    position: relative;
}
#campaign-top-navigation #ortho-elite-appoint-number .appointment-number span {
    font-size: 1.5rem;
    color: #F47920;
}
#campaign-top-navigation #ortho-elite-appoint-number {
    padding: 25px 30px 0 0;
}
#campaign-top-navigation #ortho-elite-appoint-number .appointment-number {
    color: #626161;
    font-size: 1.7rem;
    font-weight: 700;
}
.sticky {
  position: fixed;
  top: 0;
  width: 100%
}
.sticky + .content {
  padding-top: 102px;
}
</style>

<header id="navbar" role="banner" class="navbar navbar-default">
<div class="container">
    <div class="navbar-header header-scroll-logo">
      <div class="logo-wrapper">
        <a class="logo navbar-btn pull-left" href="#" title="Home">
          <img src="https://www.maxlab.co.in/pub/media/logo/websites/1/logo.png" alt="Max Lab" width="196" height="42">
        </a>
      </strong>
  </div>
  <div style="display:none;" id="campaign-top-navigation">
      <div class="region region-campaign-top-navigation">
        <section id="ortho-elite-appoint-number" class="block block-block clearfix">
          <div class="appointment-number">
            <p>Call us at <span>+91 9268 880 606</span></p>
          </div>
        </section> <!-- /.block -->
      </div>
    </div>
</div>
</header>
<style>
.carousel {
    height: 500px;
    margin-top: -20px;
}
/* Since positioning the image, we need to help out the caption */
 .carousel-caption {
    z-index: 10;
}
/* Declare heights because of positioning of img element */
 .carousel .item {
    width: 100%;
    height: 500px;
    background-color: #777;
}
.carousel-inner > .item > img {
    position: absolute;
    top: 0;
    left: 0;
    min-width: 100%;
      height: 500px;
}
.carousel-indicators .active{
  background-color: black;
}
.owl-item {
  min-width: 285px !important;
}
#top-wellness {

    width: 75%;
    overflow: hidden;
    margin-left: auto;
    margin-right: auto;
}
span.thannks-icon {
    color: #f47920;
    font-size: 6em;
    font-weight: lighter;
}
.thanks-wrapper {
    text-align: center;
    color:#003478;
}
.navbar{
  margin-bottom: 0px;
}
@media (min-width: 768px) {
    .carousel-caption p {
        margin-bottom: 20px;
        font-size: 21px;
        line-height: 1.4;
    }

}
@media (max-width: 767px)
{
  .carousel {
    height: 200px;
  }
  .carousel .item {
    height: 200px;
  }
  .carousel-inner > .item > img {
    height: 200px;
  }
  .navbar-header.header-scroll-logo {
    padding: 0px 0px;
    }
    .logo {
      min-width: 160px;
      max-width: 160px;
      margin-left: 0px;
    }
  .logo-wrapper {
    width: 200px;
    /* border: 1px solid red; */
    overflow: hidden;
    margin-left: auto;
    margin-right: auto;
    text-align: center !important;
    padding-left: 15px;
  }
  .contectme-widget-wrapper {
    position: relative;
    top: auto;
    margin-left: auto;
    margin-right: auto;
    width: 100%;
  }
  .campaign-webform{
    margin-right: 0;
  }
  .contectme-widget {
    max-width: 100%;
  }
  .col-max-4 {
    width: 50%;
  }
  .owl-item {
    min-width: 285px !important;
  }
  #top-wellness{
    width: 100%;
  }
  #wellness-packages .sec_content, #choose-max-lab .sec_content{
    padding-left: 0px;
    padding-right: 0px;
  }
  #wellness-packages .lp_container, #choose-max-lab .lp_container{
    padding-left: 0px;
    padding-right: 0px;
  }

  .ptable{width:90%;margin:0 5%;}


}
@media (max-width: 500px)
{
  .col-max-4 {
    width: 100%;
  }
}
</style>

<section id="wellness-packages" class="block block-block clearfix">
	<section class="content_section clearfix" style="background-color: #f7f7f7; margin: auto; padding: 60px 60px 100px 60px;">
    <div class="thanks-wrapper">
      <span class="thannks-icon"><i class="fa fa-check-circle-o" aria-hidden="true"></i></span>
      <h3>Thank You</h3>
    </div>
    <div class="max-labs-thank-you-page"><p style="color:#003478; font-size:25px; text-align:center;">Your submission has been received and we will contact you soon</p><button style="background:#ff5900; padding:15px 20px; margin: 15px auto;display:block;border:none;border-radius:10px; color:#fff !important;">
    <a href="https://maxlab.co.in/" style="color:#fff;"> Back To Home</a>
    </button></div>
	</section>
	<div class="footer_content clearfix">
		<div class="lp_container">
			<div class="col-max-12 sec_content why-lab">
				<h2 class="max-heading">Why Choose Max Lab</h2>
				<div class="col-max-4 box">
					<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/nurse.png'); ?>'>
						<p>Over 550 highly trained staff</p>
					</div>
					<div class="col-max-4 box">
						<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/doctor.png'); ?>'>
							<p>More Than 70 doctors trained in various sub-specialities</p>
						</div>
						<div class="col-max-4 box">
							<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/blood-sample.png'); ?>'>
								<p>Over 50 lacs samples tested, every year</p>
							</div>
						</div>
						<div class="col-max-12 sec_content why-lab">
							<div class="col-max-4 box">
								<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/lab.png'); ?>'>
									<p>Highly Qualified haematologists, histopathologists, biochemists &amp; microbiologists</p>
								</div>
								<div class="col-max-4 box">
									<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/24-hours.png'); ?>'>
										<p>24x7 free home sample collection</p>
									</div>
									<div class="col-max-4 box">
										<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/report.png'); ?>'>
											<p>Quick reporting</p>
										</div>
									</div>
									<div class="col-max-12 sec_content why-lab">
										<div class="col-max-4 box">
											<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/email.png'); ?>'>
												<p>Reports available over email</p>
											</div>
											<div class="col-max-4 box">
												<img class="icon" src='<?php echo $this->getViewFileUrl('images/icon_images/meeting.png'); ?>'>
													<p>Immediate communication of critical values to treating physician</p>
												</div>
											</div>
										</div>
									</div>

									<script>
jQuery(document).ready(function() {
	jQuery("#top-wellness .slick-track").css('width','80%');
	jQuery("#top-wellness .slick-track").css('margin','0 auto');
});

</script>
</section>


<footer class="footer container">
    <div class="region region-wrapper-bottom-footer clearfix">
    <div class="region reg-bottom-footer">
        <div class="region region-bottom-footer">
    <section id="max-copyright-block" class="block block-block clearfix">


  <div class="max-copyright-text">Copyright 2018 @ Max Lab. All rights reserved.</div>

</section> <!-- /.block -->
  </div>
    </div>
  </div>
</footer>
<div class="scroll-to-top" style="display: block;">
  <img src='<?php echo $this->getViewFileUrl('images/icon_images/white.png'); ?>'>
</div>
<script>
var jscroll = jQuery.noConflict();
jscroll(document).ready(function () {
  jscroll('.scroll-to-top').click(function () {
      jscroll("html, body").animate({
          scrollTop: 0
      }, 600);
      return false;
  });

});
</script>
<style>
footer.footer.container .region-wrapper-bottom-footer {
    background-color: #3cb9aa;
    padding: 15px 0;
    font-size: 1rem;
    text-align: center;
}
body.html>footer.container {
    width: 100%;
    max-width: 100%;
    padding: 0;
    position: relative;
}
footer.footer.container {
    width: 100%;
    padding: 0;
    margin: 0;
    background: #3cb9aa;
    color: white;
    font-size: 0;
}
body {
    font-family: "Gudea",sans-serif,Helvetica;
}
.columns .column.main {
     padding-bottom: 0px;
  }
  .block, .block-banners, .block-banners-inline {
    margin-bottom: 0px;
}
.scroll-to-top {
    background-color: #7be3d0;
    position: fixed;
    bottom: 36px;
    right: 10px;
    cursor: pointer;
    border-radius: 50%;
    height: 50px;
    width: 50px;
    padding: 5px 8px;
    text-align: center;
    overflow: hidden;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,.2), 0 6px 20px 0 rgba(0,0,0,.19);
    z-index: 999;
    bottom: 60px !important;
}
.max-copyright-text {
    font-size: 14px;
    padding: 3px;
}
.owl-item{
  display: inline-block;
}
.lp_container{
  overflow: hidden;
}
.customNavigation {
    margin-left: auto;
    margin-right: auto;
    width: 66px;
}
</style>
