<?php
$footer = $this->getConfig('vicomage_general_config/footer');
$footer_type = $this->getConfig('vicomage_general_config/footer/footer_type');
?>
<div class="footer footer-type<?php echo $footer_type; ?>">
    <?php if ($footer['footer_top']) { ?>
        <div class="footer-top">
            <?php
            if ($footer['footer_top_custom']) {
                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                if ($block) {
                    $block->setBlockId($footer['footer_top_custom']);
                }
                if ($block) {
                    echo $block->toHtml();
                }
            }
            ?>
        </div>
    <?php } ?>

    <?php if ($footer['footer_middle']) { ?>
        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <?php
                    if ($footer['footer_middle_custom']) {
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if ($block) {
                            $block->setBlockId($footer['footer_middle_custom']);
                        }
                        if ($block) {
                            echo $block->toHtml();
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    <?php } ?>

    <?php if ($footer['footer_middle_2']) { ?>
        <div class="footer-middle-2">
            <div class="container">
                <div class="row">
                    <?php
                    if ($footer['footer_middle_2_custom']) {
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if ($block) {
                            $block->setBlockId($footer['footer_middle_2_custom']);
                        }
                        if ($block) {
                            echo $block->toHtml();
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    <?php } ?>

    <?php if ($footer['footer_bottom']) { ?>
        <?php if ($footer_type == 2 || $footer_type == 3): ?>
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-mobile-12">
                            <?php echo $this->getChildHtml("footer.copyright"); ?>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-mobile-12">
                            <?php
                            if ($footer['footer_bottom_custom']) {
                                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                                if ($block) {
                                    $block->setBlockId($footer['footer_bottom_custom']);
                                }
                                if ($block) {
                                    echo $block->toHtml();
                                }
                            }
                            ?>
                            <?php if ($footer['footer_store_switcher']) { ?>
                                <?php echo $this->getChildHtml("footer.store_switcher"); ?>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($footer_type == 1 || $footer_type == 4): ?>
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-mobile-12">
                            <?php // echo $this->getChildHtml("footer.copyright"); ?>
                            <?php
                            if ($footer['footer_bottom_custom']) {
                                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                                if ($block) {
                                    $block->setBlockId($footer['footer_bottom_custom']);
                                }
                                if ($block) {
                                    echo $block->toHtml();
                                }
                            }
                            ?>
                            <?php if ($footer['footer_store_switcher']) { ?>
                                <?php echo $this->getChildHtml("footer.store_switcher"); ?>
                            <?php } ?>
						</div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php } ?>

</div>
<a id="backtotop" href="#top" style="display: block;" class=""><span class="fa fa-angle-up"></span></a>
<div class="reports-header footer-reports-buttons" >
	<div class="reportsnavleft">
		<span class="reportimage">
			<img width="40px" height="40px" src="http://maxlab.co.in/pub/media/m-phn.png">
			</span>
			<span class="reporttext12 text-white">
				<a href="tel:+8744888888" rel="nofollow">Call Us</a>
			</span>
		</div>
		<div class="reportsnavright">
			<span class="reportimage ">
				<img width="40px" height="40px" src="http://maxlab.co.in/pub/media/m-report.png">
				</span>
				<span class="reporttext2 text-white">
					<a href="https://myhealth.maxhealthcare.com/connectwebapp/login/auth" rel="nofollow" target="">Reports</a>
				</span>
			</div>
		</div>
		<style>
.footer-reports-buttons{
    display: none;
}
.text-white a{
    color: #FFFFFF !important;
}
#backtotop {
    bottom: 51px;
}
.reportsnavleft{
    border-right:1px solid #FFFFFF;
    text-align: center;
    width:50%;
}
.reportsnavright {
     width:50%;
    text-align: center;
}
@media screen and (max-width: 768px) {
    .footer-reports-buttons{
        display: block !important;
        position: fixed;
        bottom: 0px;
        width: 100%;
        margin-left: 0px;
        background: #eb7422;
        color: #FFFFFF;
        padding: 5px 10px 5px 10px;
        z-index: 999;
        border: 1px solid #fff;
    }
}
</style>