<?php //echo "Hello World"; ?>


  	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
	<!-- <script type="text/javascript" src="http://sabillon.net/jquery.mapit.js/dist/jquery.mapit.min.js"></script> -->
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.3/highlight.min.js"></script> -->
         <style>


                   select {
						width: 250px;
						padding: 3px;
						font-size: 16px;
						line-height: 1;color:#000;
						border:1px solid gray;
						border-radius: 5px;display: inline-block;text-align:left;font:inherit;
						height: 34px;
						background: url(http://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/br_down.png) no-repeat right #f8f8f8;
						-webkit-appearance: none;
						background-position-x: 224px;
					}


			/* select {
			                padding:3px;
			                border-radius:5px;
			                background: #f8f8f8;
			                color:#000;
			                border:1px solid gray;
			                outline:none;
			                display: inline-block;
			                width:250px;
			                cursor:pointer;
			                text-align:left;
			                font:inherit;
			            } */

			.filter  td{
				text-align: center;
				/* float: left */;
				margin-right: 40px;
				}

			.filter th {
				text-align: center;
				width: 33%;
			}


			  .fixed-center-table {
				table-layout: fixed;
				width: 100%;
				border-collapse: collapse;border: 1px solid gray;
				}

				.fixed-center-table  td{
				text-align: center;height: 3em;
				}
				.fixed-center-table  th{
				text-align: center;height: 3em;
				}

				col#middle-column {
				width: 40%;
				}

			</style>
         <div id="container">
                 <div class="row">
                    <div class="col-sm-5 about-intro-left">
                     <img class="img-responsive" src="/pub/media/collectioncentre.jpg" alt="" />
                    </div>
                    <div class="col-sm-7 about-intro-right">
                    <h3 style="margin-top:0;" >Max Lab&rsquo;s Collection Centers</h3>
                    <p>Max Lab franchises are the pillars of our network, which help us deliver highest quality pathology testing with full reliability and service the patients at their convenience. These exclusive collection centres allow customers to either walk-in or call for sample collection from their homes. The samples are then sent to the nearest Max Lab to perform tests at NABL accredited laboratory.
                    </p>
                    </div>
                 </div>
            <div id="body">
                <table style="margin:0 auto;width:62%;" class="filter">

                            <td align="center" height="50">

                                <label><strong>Select City</strong>
								<!-- <div class="styled-select"> -->
                                    <select name="country" onchange="showState(this);">
                                        <option value="" selected>Please Select City</option>
										<option value="1" >Delhi</option>
										<option value="12">Gurgaon</option>
										<option value="13">Noida</option>
										<option value="15">Faridabad</option>
										<option value="16">Chandigarh</option>
										<option value="17">Jalandhar</option>
										<option value="18">Ludhiana</option>
										<option value="19">Mohali</option>
										<option value="20">Patiala</option>
                                     </select>
                               <!--  </div> -->
							   </label>
                            </td>

                        <td align="center" height="50"><div id="output1"></div> </td>


                    </table>


			<table class="fixed-center-table" border="1">
			<thead>
				<colgroup>
					<col>
					<col id="middle-column">
					<col>
				</colgroup>
				<tr style="background: #003975;color: #fff;">
					<th><strong>Name</strong></th>
				  <th><strong>Address</strong></th>
				  <th><strong>Contact</strong></th>
				  <!-- <th><strong>Map</strong></th> -->
				</tr>
			</thead>

			<tbody id="output2">


			</tbody>
          </table>



          </div>
       </div>


        <script type="text/javascript">

		$(document).ready(function(){
		 //$("div.id_100 select").val("March").change();
         // var selected = $('select[name="country"]').val('1');
		  //alert('test');
		  var ccid = '1';
		  var state_id = '3';
		       //$('select[name="country"]').val("1").trigger("change");
               $.ajax({
					type: "POST",
					url: "ccenter/fetch_dstate.php",
					data: "ccid=" + ccid,
					cache: false,
					beforeSend: function() {
						$('#output1').html('<img src="ccenter/loader.gif" alt="" width="24" height="24">');
					},
					success: function(html) {
						$("#output1").html(html);
					}
				});

		   $.ajax({
				type: "POST",
				url: "ccenter/fetch_dcity.php",
				data: "state_id=" + state_id,
				cache: false,
				beforeSend: function() {
					$('#output2').html('<img src="ccenter/loader.gif" alt="" width="24" height="24">');
				},
				success: function(html) {
					$("#output2").html(html);
				}
			});

         });

					function showState(sel) {
                        var country_id = sel.options[sel.selectedIndex].value;
						//alert(country_id);
                        $("#output1").html("");
                        $("#output2").html("");

						 if (country_id == '1')
						 {
							 if (country_id.length > 0) {

								$.ajax({
									type: "POST",
									url: "ccenter/fetch_state.php",
									data: "country_id=" + country_id,
									cache: false,
									beforeSend: function() {
										$('#output1').html('<img src="ccenter/loader.gif" alt="" width="24" height="24">');
									},
									success: function(html) {
										$("#output1").html(html);
									}
								});
							  }

						 } else {
							 if (country_id.length > 0) {
								$.ajax({
									type: "POST",
									url: "ccenter/fetch_city.php",
									data: "state_id=" + country_id,
									cache: false,
									beforeSend: function() {
										$('#output2').html('<img src="ccenter/loader.gif" alt="" width="24" height="24">');
									},
									success: function(html) {
										$("#output2").html(html);
									}
								});
								} else {
									$("#output2").html("");
								}
						 }

                    }

                    function showCity(sel) {
                        var state_id = sel.options[sel.selectedIndex].value;
                        if (state_id.length > 0) {
                            $.ajax({
                                type: "POST",
                                url: "ccenter/fetch_city.php",
                                data: "state_id=" + state_id,
                                cache: false,
                                beforeSend: function() {
                                    $('#output2').html('<img src="ccenter/loader.gif" alt="" width="24" height="24">');
                                },
                                success: function(html) {
                                    $("#output2").html(html);
                                }
                            });
                        } else {
                            $("#output2").html("");
                        }
                    }
			</script>
			<!-- <script>
			$(document).ready(function(){
			 $('#demo-map').mapit();
			});
			</script>  -->
